version: "3.7"
services:
    schemeapp:
        image: gallon1/scheme
        container_name: schemeapp
        build: 
            context: .
        ports:
            - '49160:8088'
        environment:
            - NODE_ENV=docker
        volumes:
            - appdata:/usr/src/app
        links: 
            - 'schememodels:mysql'
    schememodels:
        image: mariadb
        container_name: schememodels
        environment:
            - MYSQL_DATABASE=schememodels
            - MYSQL_ROOT_PASSWORD=rootscheme
        volumes:
            - ./dbinit:/docker-entrypoint-initdb.d:ro
            - dbdata:/var/lib/mysql
        ports:
            - '3306:3306'
volumes:
    dbdata:
    appdata: