version: "3.7"
services:
    schemeapp:
        image: gallon1/scheme
        container_name: schemeapp
        build: .
        ports:
            - '49160:8088'
        environment:
            NODE_ENV: docker
        volumes:
            - .:/usr/src/app
        links: 
            - schememodels
    schememodels:
        image: mongo:latest
        container_name: schememodels
        environment:
            MONGO_INITDB_DATABASE: schememodels
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ./mongo.js:/docker-entrypoint-initdb.d/mongo.js:ro
            - ./data:/data/db
        ports:
            - '27017:27017'